### PR TITLE
Chapman border and collider physics

### PR DESCRIPTION
**Pull request by belovachap**
I was able to pull in your sprites from the email you sent, thank you!

I think our image trouble might be this problem: https://stackoverflow.com/questions/55330848/how-to-recover-corrupted-png-files-due-to-improper-gitattributes

I've been messing around a little with adding moles and then trying to fly them out of the mole hill maze (tab to jump to a random mole, W-A-S to fly the mole around like it has a little jet pack on :p).

Here's a video of it, i like the artwork you came up with :)

https://www.youtube.com/watch?v=0RHUzr7F9vU

### CODE REVIEW

**Comment by spicewooddev** [comment]
hey this is looking pretty cool! i'm feeling a lot better compared to earlier today. i had a bad reaction to the shots i got yesterday so i was feeling pretty down most of the day today.

it seems like you changed the sizes of the sprites, making the environment tiles look blurry. i can resize those so that doesn't happen, and it looks clean.

in addition, i imagined the moles would move right and left, back and forth, avoiding empty tiles and the player would drag-click to move them around to their liking. im not sure if you're thinking the same as i am, so before i end up working on that i just want to make sure we're on the same line of thinking.

**Comment by belovachap** [comment]
> hey this is looking pretty cool! i'm feeling a lot better compared to earlier today. i had a bad reaction to the shots i got yesterday so i was feeling pretty down most of the day today.
> 
> it seems like you changed the sizes of the sprites, making the environment tiles look blurry. i can resize those so that doesn't happen, and it looks clean.
> 
> in addition, i imagined the moles would move right and left, back and forth, avoiding empty tiles and the player would drag-click to move them around to their liking. im not sure if you're thinking the same as i am, so before i end up working on that i just want to make sure we're on the same line of thinking.

oh, I suppose I did scale down the moles. i thought they looked pretty sharp but i'm also not that good at design elements.

i'm not tied to how the moles move around or how the player interacts with them in the end. I just picked something that was kind of easy to implement and added a little bit of a game element to play around with.

I think this might end up being my last little bit of code committed before I head off for the birthday festivities :) I started to keep track of the number of moles killed (a lot!) and save (very few!). For fun I have the mole explode into confetti if it makes it up out of the mole hill :) Oh, and hitting "n" creates a new map by reloading the scene.

I'll keep an eye out for any pull requests you come up with today, maybe I can help you if you get stuck.

**Comment by spicewooddev** [comment]
alright. have a fun birthday celebration then! thanks for your help so far, and i should be fine working on this by myself so you can focus on your birthday.

**Comment by belovachap** [comment]
> alright. have a fun birthday celebration then! thanks for your help so far, and i should be fine working on this by myself so you can focus on your birthday.

best of luck with the remainder of the jam!

**Pull request closed without merging**
